# Generated by Django 5.1.6 on 2025-03-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
